services:
  - type: worker
    name: telegram-bot
    env: python
    pythonVersion: "3.9.0"
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      BOT_TOKEN: "8554492719:AAEfcl4fTCi3WwXe4HqKilcufJDhIqMdphg"
      ADMIN_ID: "6372922355"
      CHANNEL_LINK: "https://t.me/+0CveMZwKNsVlY2Ji"
